export const GET_PRODUCTS = 'GET_PRODUCTS'
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING'
export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_RANDOM_PRODUCT = 'GET_RANDOM_PRODUCT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'

